### ISSUE TITLE
'Commands should be idempotent' throws an error if controls are handled block wide

### ISSUE THREAD

**Issue by xoxys** [xoxys/ansible-later#9]
Shell, command and raw module a not idempotent by default and should only be used to read information and register vars) or combined with some control structures like when  or creates/removes.

This currently works only if the conditions are bound to a task directly, using a block will throw an error:
```
- block:
     - name: Run shell scrip
        shell: do something
     
     - name: ...
   when: condition
```
